name: Auto Firmware Dumper

on:
  workflow_dispatch:
    inputs:
      FIRMWARE_URL:
        description: 'Stock ROM Link'
        required: true
        default: ''
      DEVICE_CODENAME:
        description: 'Device Codename'
        required: true
        default: ''
      DEVICE_BRAND:
        description: 'Device Brand'
        required: true
        default: ''
      DEVICE_VERSION:
        description: 'Android Version'
        required: true
        default: ''
      UPLOAD_TYPE:
        description: 'Compress and publish the ROM dump to a GitLab repository or GitLab release (repo or compress)'
        required: true
        default: ''
      UPLOAD_LINEAGE_DT:
        description: 'Create LineageOS DT Repo (For approval= true)'
        required: false
        default: ''
      UPLOAD_TWRP_DT:
        description: 'Create TWRP DT Repo (For approval= true)'
        required: false
        default: ''
      USER_NAME:
        description: 'Name in GitLab Account'
        required: true
        default: ''
      USER_EMAIL:
        description: 'E-mail in GitLab Account'
        required: true
        default: ''

jobs:
  build:
    name: Auto Firmware Dumper
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-latest
    env:
      TWT: ${{ github.event.inputs.UPLOAD_TWRP_DT }}
      LOT: ${{ github.event.inputs.UPLOAD_LINEAGE_DT }}
      UT: ${{ github.event.inputs.UPLOAD_TYPE }}
      FUR: ${{ github.event.inputs.FIRMWARE_URL }}
      DCN: ${{ github.event.inputs.DEVICE_CODENAME }}
      DB: ${{ github.event.inputs.DEVICE_BRAND }}
      UN: ${{ github.event.inputs.USER_NAME }}
      UEM: ${{ github.event.inputs.USER_EMAIL }}
      AV: ${{ github.event.inputs.DEVICE_VERSION }}
      RN: dump_${{ github.event.inputs.DEVICE_BRAND }}_${{ github.event.inputs.DEVICE_CODENAME }}
    permissions:
      contents: write
    steps:
    - name: Check Out
      uses: actions/checkout@v3
      
    - name: Cleanup
      uses: rokibhasansagar/slimhub_actions@main
      
    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
       swap-size-gb: 12
        
    - name: Update Packages
      run: |
        sudo apt update
        sudo apt -y upgrade
        sudo apt -y install cpio aria2 git python3 neofetch tar xz-utils
        
    - name: Clone and Setup DumprX
      run: |
        cd /home
        sudo mkdir Auto-Dumper
        sudo chmod 777 Auto-Dumper
        cd Auto-Dumper
        git clone https://github.com/DumprX/DumprX
        cd DumprX
        sudo chmod 777 setup.sh
        sudo chmod 777 dumper.sh
        ./setup.sh

    - name: Creating Dump
      run: |
        cd /home/Auto-Dumper/DumprX
        ./dumper.sh ${{ env.FUR }}
        sudo chmod -R 777 out

    - name: Setting up git
      run: |
        git config --global user.name "${{ env.UN }}" && git config --global user.email "${{ env.UEM }}"

    - name: Uploading ROM Dump for GitLab Repository
      if: |
       github.event.inputs.UPLOAD_TYPE = repo
      run: |
        cd /home/Auto-Dumper/DumprX/out
        git lfs install
        sudo chmod -R 777 *
        check_los_dt=$(basename lineage-device-tree)
        if [ -f "$check_los_dt" ]; then
        cp -r lineage-device-tree /home/Auto-Dumper
        if [ ! -f "$check_los_dt" ]; then
        echo "No LineageOS compatible device tree found. Copying has been cancelled."
        fi;
        fi;
        check_tw_dt=$(basename twrp-device-tree)
        if [ -f "$check_tw_dt" ]; then
        cp -r twrp-device-tree /home/Auto-Dumper
        if [ ! -f "$check_tw_dt" ]; then
        echo "No TWRP compatible device tree found. Copying has been cancelled.";
        fi;
        fi;
        sudo rm -rf .git
        git init
        git branch -M android-${{ env.AV }}
        git remote add origin https://${{ secrets.GITLAB_TOKEN_NAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab.com/${{ env.UN }}/dump_${{ env.DB }}_${{ env.DCN }}.git
        find . -type f -size +75M -exec git lfs track {} +
        git add .
        git commit -s -am "${{ env.DCN }}: ROM Dump"
        git push -u origin android-${{ env.AV }}
        cd /home/Auto-Dumper
        sudo rm -rf DumprX
        
    - name: Compressing ROM Dump
      if: |
       env.UT = compress
      run: |
        cd /home/Auto-Dumper/DumprX/out
        echo "Compressing dump..."
        tar cJvf dump_${{ env.DB }}_${{ env.DCN }}.tar.xz *
        echo "Dump has been compressed successfully. Format: tar.xz"
        cp dump_${{ env.DB }}_${{ env.DCN }}.tar.xz /home/Auto-Dumper
        echo "Unnecessary old files are deleted..."
        cd /home/Auto-Dumper
        sudo rm -rf DumprX

    - name: Uploading LineageOS Device Tree
      if: |
        ${{ env.LOT }} = true
      run: |
        if [ ! -f "$check_los_dt" ]; then
        echo "No LineageOS compatible device tree found. Pushing canceled."
        fi;
        if [ -f "$check_los_dt" ]; then
        cd /home/Auto-Dumper
        wget https://raw.githubusercontent.com/YZBruh/Auto-Firmware-Dumper/master/scripts/control_lineage_dt.sh
        sudo chmod 777 control_lineage_dt.sh
        ./control_lineage_dt.sh
        fi;

    - name: Uploading TWRP Device Tree
      if: |
        env.TWT = true
      run: |
        if [ ! -f "$check_tw_dt" ]; then
        echo "No TWRP compatible device tree found. Pushing canceled."
        fi;
        if [ -f "$check_tw_dt" ]; then
        cd /home/Auto-Dumper
        wget https://raw.githubusercontent.com/YZBruh/Auto-Firmware-Dumper/master/scripts/control_twrp_dt.sh
        sudo chmod 777 control_twrp_dt.sh
        ./control_twrp_dt.sh
        fi;

    - name: Uploading Compressed ROM Dump
      if: |
       env.UT = compress
      uses: softprops/action-gh-release@v1
      with:
        files: | 
          /home/Auto-Dumper/DumprX
        name: ROM dump for ${{ env.DB }} ${{ env.DCN }} - ${{ github.run_id }}
        tag_name: ${{ env.DCN }}_${{ github.run_id }}
        body: |
           Device: ${{ env.DCN }}
           Brand: ${{ env.DB }}
           Android version: ${{ env.AV }}
           TWRP Tree repo: ${{ env.TWT }}
           LineageOS Tree repo: ${{ env.LOT }}
